import type { Board, GraphData } from "./types";
/**
 * Seed content for local demo mode (no backend required). Themed around a
 * "Motor Design" board, showcasing every node type, tasks, a project and a
 * second board so the app feels real on first load.
 */
const t = new Date().toISOString();

// Helper to build ISO date strings relative to today
function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}
function daysFromNow(n: number) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}
function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

// Build habit logs for the last 30 days with realistic patterns
function buildHabitLog(hitRate: number, days = 30): string[] {
  const log: string[] = [];
  for (let i = 0; i < days; i++) {
    if (Math.random() < hitRate) {
      log.push(daysAgo(i));
    }
  }
  // Always include today for high-rate habits
  if (hitRate > 0.7 && !log.includes(todayStr())) {
    log.push(todayStr());
  }
  return log;
}

export const DEMO_BOARDS: Board[] = [
  { id: "b_motor", title: "BLDC Motor Control", color: "#e0e0e0", updatedAt: t },
  { id: "b_ai", title: "AI Research Assistant", color: "#b9a7ff", updatedAt: t },
  { id: "b_app", title: "Mobile App Redesign", color: "#8fb6e0", updatedAt: t },
  { id: "b_yt", title: "YouTube Content System", color: "#8fd0a0", updatedAt: t },
];
export const DEMO_CURRENT_BOARD = "b_motor";
export const DEMO_GRAPH: GraphData = {
  nodes: [
    // ---- Projects ----
    {
      id: "n_project",
      type: "project",
      title: "BLDC Motor Control",
      content: "2.4 kW continuous, field-oriented control. Target tape-out of the controller board by Q3.",
      tags: ["hardware", "project"],
      boardId: "b_motor",
      x: -40, y: -300, w: 300, h: 170,
      updatedAt: t,
    },
    {
      id: "n_project_ai",
      type: "project",
      title: "AI Research Assistant",
      content: "Building an AI-powered research assistant with RAG and knowledge graph integration.",
      tags: ["ai", "project"],
      boardId: "b_ai",
      x: 0, y: 0, w: 300, h: 170,
      updatedAt: t,
    },
    {
      id: "n_project_app",
      type: "project",
      title: "Mobile App Redesign",
      content: "Complete UI/UX overhaul of the mobile app with new design system.",
      tags: ["design", "project"],
      boardId: "b_app",
      x: 0, y: 0, w: 300, h: 170,
      updatedAt: t,
    },
    {
      id: "n_project_yt",
      type: "project",
      title: "YouTube Content System",
      content: "Automated content pipeline for YouTube channel growth.",
      tags: ["content", "project"],
      boardId: "b_yt",
      x: 0, y: 0, w: 300, h: 170,
      updatedAt: t,
    },
    // ---- Notes ----
    {
      id: "n_motor",
      type: "note",
      title: "Motor Design",
      content: "# Motor Design\n\nCentral hub for the brushless motor project. Targeting **2.4 kW** continuous output with field-oriented control.\n\nLinks: [[Thermal Model]] · [[Winding Layout]] · [[Controller Firmware]]",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 0, y: 0, w: 280, h: 180,
      updatedAt: t,
    },
    {
      id: "n_thermal",
      type: "note",
      title: "Thermal Model",
      content: "Steady-state thermal budget. Copper losses dominate at peak torque. Need forced-air over the stator. See [[Motor Design]].",
      tags: ["analysis"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 400, y: -120, w: 260, h: 160,
      updatedAt: t,
    },
    {
      id: "n_winding",
      type: "note",
      title: "Winding Layout",
      content: "Distributed 12-slot / 8-pole winding. Fill factor ~0.45. Hairpin option deferred to v2. Feeds [[Thermal Model]].",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 400, y: 120, w: 260, h: 160,
      updatedAt: t,
    },
    {
      id: "n_firmware",
      type: "note",
      title: "Controller Firmware",
      content: "FOC loop at 20 kHz on STM32G4. SVPWM + sensorless observer below 5% speed. Depends on [[Motor Design]].",
      tags: ["software"],
      boardId: "b_motor",
      projectId: "n_project",
      x: -380, y: 60, w: 260, h: 160,
      updatedAt: t,
    },
    {
      id: "n_note_ai_research",
      type: "note",
      title: "BLDC Motor Control Research",
      content: "Research notes on field-oriented control algorithms and implementation strategies.",
      tags: ["research", "hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 200, y: -400, w: 280, h: 160,
      updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    },
    {
      id: "n_note_phoenix",
      type: "note",
      title: "Project Phoenix Plan",
      content: "Strategic planning document for the next phase of the project.",
      tags: ["planning"],
      boardId: "b_motor",
      x: -200, y: -400, w: 280, h: 160,
      updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    },
    {
      id: "n_note_user_interview",
      type: "note",
      title: "User Interview Insights",
      content: "Key findings from user research interviews conducted this week.",
      tags: ["research", "ux"],
      boardId: "b_app",
      x: 0, y: 300, w: 280, h: 160,
      updatedAt: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    },
    {
      id: "n_note_daily",
      type: "note",
      title: "Daily Journal – Yesterday",
      content: "Reflections on the day. Made good progress on the motor control firmware.",
      tags: ["daily", "journal"],
      boardId: "b_motor",
      x: -400, y: 300, w: 280, h: 160,
      updatedAt: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    },
    {
      id: "n_note_marketing",
      type: "note",
      title: "Marketing Strategy 2024",
      content: "Content marketing strategy and distribution channels for 2024.",
      tags: ["marketing", "strategy"],
      boardId: "b_yt",
      x: 300, y: 300, w: 280, h: 160,
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
    },
    // ---- Tasks ----
    {
      id: "n_task_bench",
      type: "task",
      title: "Finalize motor design",
      content: "Complete the final motor design specifications.",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      status: "todo",
      priority: "high",
      due: todayStr(),
      x: -200, y: 300, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_review",
      type: "task",
      title: "Review BLDC research paper",
      content: "Read and annotate the latest BLDC control research paper.",
      tags: ["research"],
      boardId: "b_motor",
      projectId: "n_project",
      status: "todo",
      priority: "med",
      due: todayStr(),
      x: 200, y: 300, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_workout",
      type: "task",
      title: "Workout",
      content: "Morning workout session.",
      tags: ["fitness"],
      boardId: "b_motor",
      status: "todo",
      priority: "med",
      due: todayStr(),
      x: 0, y: 500, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_client",
      type: "task",
      title: "Client presentation",
      content: "Prepare and deliver client presentation.",
      tags: ["work"],
      boardId: "b_motor",
      status: "todo",
      priority: "high",
      due: todayStr(),
      x: -400, y: 500, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_journal",
      type: "task",
      title: "Write weekly journal",
      content: "Weekly reflection and planning journal entry.",
      tags: ["personal"],
      boardId: "b_motor",
      status: "todo",
      priority: "low",
      due: todayStr(),
      x: 400, y: 500, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_scope",
      type: "task",
      title: "Define project scope",
      content: "Define the scope and requirements for the AI research assistant.",
      tags: ["planning"],
      boardId: "b_ai",
      projectId: "n_project_ai",
      status: "done",
      priority: "high",
      due: daysAgo(3),
      x: -200, y: 300, w: 260, h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_mvp",
      type: "task",
      title: "Build MVP",
      content: "Build the minimum viable product for the AI research assistant.",
      tags: ["development"],
      boardId: "b_ai",
      projectId: "n_project_ai",
      status: "doing",
      priority: "high",
      due: daysFromNow(5),
      x: 200, y: 300, w: 260, h: 120,
      updatedAt: t,
    },
    // ---- Events ----
    {
      id: "n_event_standup",
      type: "event",
      title: "Team Standup",
      content: "Daily team standup meeting.",
      tags: ["meeting"],
      boardId: "b_motor",
      due: todayStr() + "T10:00:00",
      x: -600, y: 0, w: 260, h: 130,
      updatedAt: t,
    },
    {
      id: "n_event_client",
      type: "event",
      title: "Client Presentation",
      content: "Present the motor control project to the client.",
      tags: ["meeting", "client"],
      boardId: "b_motor",
      due: todayStr() + "T14:00:00",
      x: -600, y: 200, w: 260, h: 130,
      updatedAt: t,
    },
    {
      id: "n_event_review",
      type: "event",
      title: "Product Review",
      content: "Weekly product review and retrospective.",
      tags: ["meeting"],
      boardId: "b_motor",
      due: todayStr() + "T16:30:00",
      x: -600, y: 400, w: 260, h: 130,
      updatedAt: t,
    },
    // ---- Habits ----
    {
      id: "n_habit_workout",
      type: "habit",
      title: "Morning Workout",
      content: "30 minutes of exercise every morning.",
      tags: ["fitness", "health"],
      boardId: "b_motor",
      cadence: "daily",
      category: "Health",
      habitLog: buildHabitLog(0.92, 30),
      x: -800, y: 0, w: 260, h: 140,
      updatedAt: t,
    },
    {
      id: "n_habit_reading",
      type: "habit",
      title: "Read 20 Pages",
      content: "Read at least 20 pages of a book every day.",
      tags: ["learning", "reading"],
      boardId: "b_motor",
      cadence: "daily",
      category: "Learning",
      habitLog: buildHabitLog(0.85, 30),
      x: -800, y: 200, w: 260, h: 140,
      updatedAt: t,
    },
    {
      id: "n_habit_meditation",
      type: "habit",
      title: "Meditation",
      content: "10 minutes of mindfulness meditation.",
      tags: ["mindfulness", "health"],
      boardId: "b_motor",
      cadence: "daily",
      category: "Mindfulness",
      habitLog: buildHabitLog(0.72, 30),
      x: -800, y: 400, w: 260, h: 140,
      updatedAt: t,
    },
    {
      id: "n_habit_water",
      type: "habit",
      title: "Drink 2L Water",
      content: "Stay hydrated with 2 liters of water daily.",
      tags: ["health", "hydration"],
      boardId: "b_motor",
      cadence: "daily",
      category: "Health",
      habitLog: buildHabitLog(0.65, 30),
      x: -800, y: 600, w: 260, h: 140,
      updatedAt: t,
    },
    {
      id: "n_habit_sugar",
      type: "habit",
      title: "No Sugar",
      content: "Avoid added sugar in diet.",
      tags: ["health", "diet"],
      boardId: "b_motor",
      cadence: "daily",
      category: "Diet",
      habitLog: buildHabitLog(0.55, 30),
      x: -800, y: 800, w: 260, h: 140,
      updatedAt: t,
    },
    // ---- Knowledge nodes ----
    {
      id: "n_render",
      type: "image",
      title: "Motor render v3",
      content: "3D render of the motor assembly.",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 760, y: -200, w: 280, h: 200,
      updatedAt: t,
    },
    {
      id: "n_research",
      type: "research",
      title: "Sensorless below 5% speed?",
      content: "Investigate HF injection vs. observer blending for low-speed sensorless control.",
      tags: ["research"],
      boardId: "b_motor",
      sources: [
        { title: "FOC of PMSM — survey", url: "https://example.com/foc-survey" },
        { title: "HF injection methods", url: "https://example.com/hf-injection" },
      ],
      x: 720, y: 0, w: 300, h: 220,
      updatedAt: t,
    },
    {
      id: "n_voice",
      type: "voice",
      title: "Lab note — bearing noise",
      content: "Transcript: heard a whine around 8k rpm, likely the rear bearing preload. Check shim stack.",
      tags: ["lab"],
      boardId: "b_motor",
      x: 320, y: -320, w: 260, h: 130,
      updatedAt: t,
    },
    {
      id: "n_pdf",
      type: "pdf",
      title: "STM32G4 Reference Manual",
      content: "RM0440 — timers, ADC, and the high-resolution timer (HRTIM).",
      src: "https://example.com/rm0440.pdf",
      tags: ["datasheet"],
      boardId: "b_motor",
      x: -760, y: -120, w: 280, h: 300,
      updatedAt: t,
    },
    // ---- Reading / AI board ----
    {
      id: "n_read_1",
      type: "link",
      title: "The Bitter Lesson",
      content: "Rich Sutton on scaling vs. hand-crafted knowledge.",
      src: "https://example.com/bitter-lesson",
      tags: ["ml"],
      boardId: "b_ai",
      x: 0, y: 0, w: 260, h: 110,
      updatedAt: t,
    },
    {
      id: "n_read_2",
      type: "note",
      title: "Spaced repetition",
      content: "Notes on SM-2 and FSRS scheduling. Relates to [[The Bitter Lesson]].",
      tags: ["learning"],
      boardId: "b_ai",
      x: 320, y: 40, w: 280, h: 160,
      updatedAt: t,
    },
  ],
  edges: [
    { id: "e1", source: "n_motor", target: "n_thermal", kind: "wikilink", status: "active" },
    { id: "e2", source: "n_motor", target: "n_winding", kind: "wikilink", status: "active" },
    { id: "e3", source: "n_motor", target: "n_firmware", kind: "wikilink", status: "active" },
    { id: "e4", source: "n_winding", target: "n_thermal", kind: "wikilink", status: "active" },
    { id: "e5", source: "n_project", target: "n_motor", kind: "arrow", status: "active" },
    { id: "e6", source: "n_firmware", target: "n_pdf", kind: "reference", status: "active" },
    { id: "e7", source: "n_firmware", target: "n_research", kind: "reference", status: "active" },
    { id: "e8", source: "n_thermal", target: "n_render", kind: "arrow", status: "active" },
    { id: "e9", source: "n_project", target: "n_task_bench", kind: "reference", status: "active" },
    { id: "e10", source: "n_project", target: "n_task_review", kind: "reference", status: "active" },
    { id: "e11", source: "n_motor", target: "n_note_ai_research", kind: "reference", status: "active" },
    { id: "e12", source: "n_thermal", target: "n_voice", kind: "ai_suggested", confidence: 0.72, status: "suggested" },
    { id: "e13", source: "n_firmware", target: "n_note_ai_research", kind: "ai_suggested", confidence: 0.65, status: "suggested" },
  ],
};
