import type { Board, GraphData } from "./types";

/**
 * Seed content for local demo mode (no backend required). Themed around a
 * "Motor Design" board, showcasing every node type, tasks, a project and a
 * second board so the app feels real on first load.
 */

const t = new Date().toISOString();

export const DEMO_BOARDS: Board[] = [
  { id: "b_motor", title: "Motor Design", color: "#e0e0e0", updatedAt: t },
  { id: "b_reading", title: "Reading List", color: "#8fb6e0", updatedAt: t },
];

export const DEMO_CURRENT_BOARD = "b_motor";

export const DEMO_GRAPH: GraphData = {
  nodes: [
    // ---- Motor Design board ----
    {
      id: "n_project",
      type: "project",
      title: "Brushless Motor v1",
      content:
        "2.4 kW continuous, field-oriented control. Target tape-out of the controller board by Q3.",
      tags: ["hardware", "project"],
      boardId: "b_motor",
      x: -40,
      y: -300,
      w: 300,
      h: 170,
      updatedAt: t,
    },
    {
      id: "n_motor",
      type: "note",
      title: "Motor Design",
      content:
        "# Motor Design\n\nCentral hub for the brushless motor project. Targeting **2.4 kW** continuous output with field-oriented control.\n\nLinks: [[Thermal Model]] · [[Winding Layout]] · [[Controller Firmware]]",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 0,
      y: 0,
      w: 280,
      h: 180,
      updatedAt: t,
    },
    {
      id: "n_thermal",
      type: "note",
      title: "Thermal Model",
      content:
        "Steady-state thermal budget. Copper losses dominate at peak torque. Need forced-air over the stator. See [[Motor Design]].",
      tags: ["analysis"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 400,
      y: -120,
      w: 260,
      h: 160,
      updatedAt: t,
    },
    {
      id: "n_winding",
      type: "note",
      title: "Winding Layout",
      content:
        "Distributed 12-slot / 8-pole winding. Fill factor ~0.45. Hairpin option deferred to v2. Feeds [[Thermal Model]].",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      x: 400,
      y: 120,
      w: 260,
      h: 160,
      updatedAt: t,
    },
    {
      id: "n_firmware",
      type: "note",
      title: "Controller Firmware",
      content:
        "FOC loop at 20 kHz on STM32G4. SVPWM + sensorless observer below 5% speed. Depends on [[Motor Design]].",
      tags: ["software"],
      boardId: "b_motor",
      projectId: "n_project",
      x: -380,
      y: 60,
      w: 260,
      h: 160,
      updatedAt: t,
    },
    {
      id: "n_task_bench",
      type: "task",
      title: "Build dyno test bench",
      content: "Source a 5 kW load bank and torque transducer.",
      tags: ["hardware"],
      boardId: "b_motor",
      projectId: "n_project",
      status: "doing",
      priority: "high",
      due: new Date(Date.now() + 6 * 864e5).toISOString(),
      x: -380,
      y: 280,
      w: 260,
      h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_foc",
      type: "task",
      title: "Tune FOC current loop",
      content: "Set Kp/Ki from motor R and L. Verify step response.",
      tags: ["software"],
      boardId: "b_motor",
      projectId: "n_project",
      status: "todo",
      priority: "med",
      x: -80,
      y: 280,
      w: 260,
      h: 120,
      updatedAt: t,
    },
    {
      id: "n_task_safe",
      type: "task",
      title: "Add overcurrent protection",
      content: "Hardware comparator + firmware fault latch.",
      tags: ["safety"],
      boardId: "b_motor",
      projectId: "n_project",
      status: "done",
      priority: "high",
      x: 220,
      y: 280,
      w: 260,
      h: 120,
      updatedAt: t,
    },
    {
      id: "n_render",
      type: "image",
      title: "Rotor Render",
      content: "Concept render of the rotor assembly.",
      src: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=70",
      tags: ["reference"],
      boardId: "b_motor",
      x: -420,
      y: -220,
      w: 240,
      h: 180,
      updatedAt: t,
    },
    {
      id: "n_research",
      type: "research",
      title: "Sensorless below 5% speed?",
      content:
        "Investigate HF injection vs. observer blending for low-speed sensorless control.",
      tags: ["research"],
      boardId: "b_motor",
      sources: [
        { title: "FOC of PMSM — survey", url: "https://example.com/foc-survey" },
        { title: "HF injection methods", url: "https://example.com/hf-injection" },
      ],
      x: 720,
      y: 0,
      w: 300,
      h: 220,
      updatedAt: t,
    },
    {
      id: "n_voice",
      type: "voice",
      title: "Lab note — bearing noise",
      content:
        "Transcript: heard a whine around 8k rpm, likely the rear bearing preload. Check shim stack.",
      tags: ["lab"],
      boardId: "b_motor",
      x: 320,
      y: -320,
      w: 260,
      h: 130,
      updatedAt: t,
    },
    {
      id: "n_pdf",
      type: "pdf",
      title: "STM32G4 Reference Manual",
      content: "RM0440 — timers, ADC, and the high-resolution timer (HRTIM).",
      src: "https://example.com/rm0440.pdf",
      tags: ["datasheet"],
      boardId: "b_motor",
      x: -760,
      y: -120,
      w: 280,
      h: 300,
      updatedAt: t,
    },

    // ---- Reading List board ----
    {
      id: "n_read_1",
      type: "link",
      title: "The Bitter Lesson",
      content: "Rich Sutton on scaling vs. hand-crafted knowledge.",
      src: "https://example.com/bitter-lesson",
      tags: ["ml"],
      boardId: "b_reading",
      x: 0,
      y: 0,
      w: 260,
      h: 110,
      updatedAt: t,
    },
    {
      id: "n_read_2",
      type: "note",
      title: "Spaced repetition",
      content:
        "Notes on SM-2 and FSRS scheduling. Relates to [[The Bitter Lesson]].",
      tags: ["learning"],
      boardId: "b_reading",
      x: 320,
      y: 40,
      w: 280,
      h: 160,
      updatedAt: t,
    },
  ],
  edges: [
    { id: "e1", source: "n_motor", target: "n_thermal", kind: "wikilink", status: "active" },
    { id: "e2", source: "n_motor", target: "n_winding", kind: "wikilink", status: "active" },
    { id: "e3", source: "n_motor", target: "n_firmware", kind: "wikilink", status: "active" },
    { id: "e4", source: "n_winding", target: "n_thermal", kind: "wikilink", status: "active" },
    { id: "e5", source: "n_project", target: "n_motor", kind: "arrow", status: "active" },
    { id: "e6", source: "n_firmware", target: "n_pdf", kind: "reference", status: "active" },
    { id: "e7", source: "n_firmware", target: "n_research", kind: "reference", status: "active" },
    { id: "e8", source: "n_thermal", target: "n_render", kind: "arrow", status: "active" },
    {
      id: "e9",
      source: "n_thermal",
      target: "n_voice",
      kind: "ai_suggested",
      confidence: 0.72,
      status: "suggested",
    },
  ],
};
